# Generated by Django 3.2.2 on 2021-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('actice', 'active'), ('inactive', 'inactive')], max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('actice', 'active'), ('inactive', 'inactive')], max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('actice', 'active'), ('inactive', 'inactive')], max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('hot', 'hot'), ('', 'default')], max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('actice', 'active'), ('inactive', 'inactive')], max_length=200),
        ),
    ]
