# Generated by Django 3.2.2 on 2021-05-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210509_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('actice', 'active'), ('inactive', 'inactive')], max_length=200),
        ),
    ]
