# Generated by Django 3.2.2 on 2021-05-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210514_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
