# Generated by Django 3.2.2 on 2021-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('discription', models.TextField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=200)),
            ],
        ),
    ]
