# Generated by Django 3.2.2 on 2021-05-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
