# Generated by Django 3.2.2 on 2021-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
