# Generated by Django 4.0.4 on 2022-05-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_orderitem_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='add',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone',
        ),
    ]
