# Generated by Django 4.0.4 on 2022-06-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_orderitem_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default='KTM', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='user', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='phone',
            field=models.CharField(default=9800000, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
