# Generated by Django 4.0.4 on 2022-06-12 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_item_discounted_price_alter_item_price'),
        ('cart', '0017_orderitem_address_orderitem_email_orderitem_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('Pay With Khalti', 'Pay With Khalti'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancel')], default='Delivered', max_length=200)),
                ('name', models.CharField(default='user', max_length=200)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('address', models.CharField(default='KTM', max_length=200)),
                ('phone', models.CharField(default=9800000, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
    ]
