# Generated by Django 4.0.4 on 2022-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancel')], default='Delivered', max_length=100),
        ),
    ]
