# Generated by Django 4.0.4 on 2022-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_alter_orderhistry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistry',
            name='time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancel')], default='Delivered', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
