# Generated by Django 4.0.4 on 2022-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='time',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
