# Generated by Django 4.0.4 on 2022-06-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_remove_orderitem_time_orderitem_order_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistry',
            name='time',
        ),
        migrations.AddField(
            model_name='orderhistry',
            name='purchase_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
